{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOUAcfPzeE+YU7OquDEHtSd"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import random\n",
        "\n",
        "board = [\" \"] * 9\n",
        "\n",
        "def display_board():\n",
        "    print()\n",
        "    print(board[0] + \" | \" + board[1] + \" | \" + board[2])\n",
        "    print(\"--+---+--\")\n",
        "    print(board[3] + \" | \" + board[4] + \" | \" + board[5])\n",
        "    print(\"--+---+--\")\n",
        "    print(board[6] + \" | \" + board[7] + \" | \" + board[8])\n",
        "    print()\n",
        "\n",
        "def check_winner(player):\n",
        "    winning_positions = [\n",
        "        [0, 1, 2],\n",
        "        [3, 4, 5],\n",
        "        [6, 7, 8],\n",
        "        [0, 3, 6],\n",
        "        [1, 4, 7],\n",
        "        [2, 5, 8],\n",
        "        [0, 4, 8],\n",
        "        [2, 4, 6]\n",
        "    ]\n",
        "    for position in winning_positions:\n",
        "        if (board[position[0]] == player and\n",
        "            board[position[1]] == player and\n",
        "            board[position[2]] == player):\n",
        "            return True\n",
        "    return False\n",
        "\n",
        "def board_full():\n",
        "    return \" \" not in board\n",
        "\n",
        "def find_winning_move(player):\n",
        "    for i in range(9):\n",
        "        if board[i] == \" \":\n",
        "            board[i] = player\n",
        "            if check_winner(player):\n",
        "                board[i] = \" \"\n",
        "                return i\n",
        "            board[i] = \" \"\n",
        "    return None\n",
        "print(\"TIC-TAC-TOE\")\n",
        "print(\"You are X. Computer is O.\")\n",
        "\n",
        "while True:\n",
        "\n",
        "    display_board()\n",
        "\n",
        "    while True:\n",
        "        try:\n",
        "            choice = int(input(\"Enter position (1-9): \"))\n",
        "\n",
        "            if choice < 1 or choice > 9:\n",
        "                print(\"Enter a number between 1 and 9.\")\n",
        "\n",
        "            elif board[choice - 1] != \" \":\n",
        "                print(\"Position already occupied.\")\n",
        "\n",
        "            else:\n",
        "                board[choice - 1] = \"X\"\n",
        "                break\n",
        "\n",
        "        except ValueError:\n",
        "            print(\"Please enter a number.\")\n",
        "\n",
        "    if check_winner(\"X\"):\n",
        "        display_board()\n",
        "        print(\"Player wins!\")\n",
        "        break\n",
        "\n",
        "    if board_full():\n",
        "        display_board()\n",
        "        print(\"Draw!\")\n",
        "        break\n",
        "\n",
        "    computer_position = find_winning_move(\"O\")\n",
        "\n",
        "\n",
        "    if computer_position is None:\n",
        "        empty_positions = []\n",
        "\n",
        "        for i in range(9):\n",
        "            if board[i] == \" \":\n",
        "                empty_positions.append(i)\n",
        "\n",
        "        computer_position = random.choice(empty_positions)\n",
        "\n",
        "    board[computer_position] = \"O\"\n",
        "\n",
        "    print(\"Computer chose position:\", computer_position + 1)\n",
        "\n",
        "    if check_winner(\"O\"):\n",
        "        display_board()\n",
        "        print(\"Computer wins!\")\n",
        "        break\n",
        "\n",
        "    if board_full():\n",
        "        display_board()\n",
        "        print(\"Draw!\")\n",
        "        break\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "w5-ORRDv9kBv",
        "outputId": "62a0867f-48f9-4b99-f6ea-150156031a10"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "TIC-TAC-TOE\n",
            "You are X. Computer is O.\n",
            "\n",
            "  |   |  \n",
            "--+---+--\n",
            "  |   |  \n",
            "--+---+--\n",
            "  |   |  \n",
            "\n",
            "Enter position (1-9): 1\n",
            "Computer chose position: 7\n",
            "\n",
            "X |   |  \n",
            "--+---+--\n",
            "  |   |  \n",
            "--+---+--\n",
            "O |   |  \n",
            "\n",
            "Enter position (1-9): 4\n",
            "Computer chose position: 2\n",
            "\n",
            "X | O |  \n",
            "--+---+--\n",
            "X |   |  \n",
            "--+---+--\n",
            "O |   |  \n",
            "\n",
            "Enter position (1-9): 5\n",
            "Computer chose position: 3\n",
            "\n",
            "X | O | O\n",
            "--+---+--\n",
            "X | X |  \n",
            "--+---+--\n",
            "O |   |  \n",
            "\n",
            "Enter position (1-9): 9\n",
            "\n",
            "X | O | O\n",
            "--+---+--\n",
            "X | X |  \n",
            "--+---+--\n",
            "O |   | X\n",
            "\n",
            "Player wins!\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bUH1rmHx823A",
        "outputId": "25d3ed09-1bae-42b7-8064-7242d6faad46"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Vacuum is in Room A\n",
            "Room A: Dirty\n",
            "Room B: Dirty\n",
            "Action: SUCK\n",
            "\n",
            "Vacuum is in Room A\n",
            "Room A: Clean\n",
            "Room B: Dirty\n",
            "Action: MOVE RIGHT\n",
            "\n",
            "Vacuum is in Room B\n",
            "Room A: Clean\n",
            "Room B: Dirty\n",
            "Action: SUCK\n",
            "\n",
            "Both rooms are clean.\n",
            "Goal achieved!\n"
          ]
        }
      ],
      "source": [
        "rooms = {\n",
        "    \"A\": \"Dirty\",\n",
        "    \"B\": \"Dirty\"\n",
        "}\n",
        "\n",
        "position = \"A\"\n",
        "\n",
        "while True:\n",
        "\n",
        "    print(\"\\nVacuum is in Room\", position)\n",
        "    print(\"Room A:\", rooms[\"A\"])\n",
        "    print(\"Room B:\", rooms[\"B\"])\n",
        "\n",
        "    if rooms[position] == \"Dirty\":\n",
        "        print(\"Action: SUCK\")\n",
        "        rooms[position] = \"Clean\"\n",
        "\n",
        "    elif position == \"A\":\n",
        "        print(\"Action: MOVE RIGHT\")\n",
        "        position = \"B\"\n",
        "\n",
        "    else:\n",
        "        print(\"Action: MOVE LEFT\")\n",
        "        position = \"A\"\n",
        "\n",
        "    if rooms[\"A\"] == \"Clean\" and rooms[\"B\"] == \"Clean\":\n",
        "        print(\"\\nBoth rooms are clean.\")\n",
        "        print(\"Goal achieved!\")\n",
        "        break"
      ]
    }
  ]
}